export enum COURIER_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum COURIER_OPERATIONAL_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  LOCKED = 'LOCKED',
}

export const COURIER_REGISTRATION_OTP = 'COURIER_REGISTRATION_OTP' as const;
